### ISSUE TITLE
Colors doesen't change

### ISSUE THREAD

**Issue by Yupy** [PapirusDevelopmentTeam/papirus-folders#1]
I have and issue I use openSUSE KDE I did replaced to colors to GREEN but nothing change.

See: https://imgur.com/a/VeCOk

**Comment by SmartFinn** [comment]
Try to update icon cache and to log out and then log back in again for this change to take effect.

```
papirus-folders -u --theme Papirus
```

Also, make sure you use Papirus instead Papirus-Dark or whatever.

**Comment by Yupy** [comment]
Thank you for the reply, but the icons are still blue it could be the cache?

I also logget out and rebooted the system.

**Comment by SmartFinn** [comment]
What folder color in Dolphin now?

There are a few possible issues:

1. The wrong icon theme was specified
2. The icons cache wasn't updated
3. Papirus icons were installed in two or more places (root and home directory for example)

**Comment by Yupy** [comment]
The folder color in Dolphin is Blue
The icon theme specified is Papirus
I also deleted the cache file from the Papirus icons folder
And the icons are installed in /usr/share/icons/ (root)

**Comment by Yupy** [comment]
Thanks for the heads up I found the "culprit" the icon theme was also in Home IDK how it got there.

Thanks again and I wish you a nice day!
