### ISSUE TITLE
Error: Unable to find 'indigo' color in 'Papirus'

### ISSUE THREAD

**Issue by Nullified2** [PapirusDevelopmentTeam/papirus-folders#12]
Has the indigo colour scheme been added yet? because it's unable to find it.

Thanks!

**Comment by Nullified2** [comment]
I have noticed it for a while but never submitted a bug report until now

**Comment by SmartFinn** [comment]
The indigo folders come with papirus-icon-theme `20190213`. Just update the icon theme with [Papirus Installer](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#root-directory-recommended) or wait ~16 hours until the new release will be published in our PPA.

**Comment by Nullified2** [comment]
Alright, I will wait then.
