### ISSUE TITLE
Void Linux package

### ISSUE THREAD

**Issue by DarthWound** [PapirusDevelopmentTeam/papirus-folders#13]
Hello, there is a package for Void since a couple of days :-)

| **Distro** | **Maintainer** | **Package**  |
| :--------- | :------------- | :----------- |
| Void Linux | Benjamín Albiñana | `sudo xbps-install -S papirus-folders` <sup>srcpkgs [[link](https://github.com/void-linux/void-packages/tree/master/srcpkgs/papirus-folders)]</sub> |

```
| Void Linux | Benjamín Albiñana | `sudo xbps-install -S papirus-folders` <sup>srcpkgs [[link](https://github.com/void-linux/void-packages/tree/master/srcpkgs/papirus-folders)]</sub> |
```

**Comment by SmartFinn** [comment]
Nice to see it. Thanks for the package request. I'll add it, but don't see a point to add a link to build instruction when it's not a community-driven package.

**Comment by DarthWound** [comment]
Thanks for adding it :)
