### ISSUE TITLE
Change all folder colors (Cinnamon/Nemo)

### ISSUE THREAD

**Issue by trymeouteh** [PapirusDevelopmentTeam/papirus-folders#14]
Is there a way to change all the folder colors in Cinnamon and Nemo without having to select every single folder and changinf its color?

I am using Linux Mint 19.2 and I would like to use Papirus icon pack but with my folder icons to be Green and not Teal.

**Comment by SmartFinn** [comment]
We have a script to change the colors of the folders. Just install it from this repo https://github.com/PapirusDevelopmentTeam/papirus-folders

**Comment by SmartFinn** [comment]
Ha, I just did notice in which repo you asked :) But now I don't understand your question.

**Comment by trymeouteh** [comment]
When you launch the Themes app in Cinnamon you can change your theme including your icons. By default in Linux Mint it is set to Mint-Y. There are many icons to choose from out of the box such as Mint-Y-Teal, Mint-Y-Blue, Mint-Y-Red and so on. These icons packs will change the color the default folder color.

I installed the Papirus icon pack and it does not come with different color packs, it says I need to use folder colors to change the color. But all that folder colors can do to my understanding is change individual folder colors and not change the default folder color.

The Papirus icon pack default folder color is Teal, I would like it to be green so it will match with the Linux Mint theme.

Is there a way to change all the folder colors in the Papirus icon pack to green?

**Comment by SmartFinn** [comment]
@trymeouteh 

> But all that folder colors can do to my understanding is change individual folder colors and not change the default folder color.

The papirus-folder script changes the default folder color.

> When you launch the Themes app in Cinnamon you can change your theme including your icons.

We can't provide that way because it requires to create 4 base themes × 17 colors = 68 themes.

> The Papirus icon pack default folder color is Teal

Actually the default color is Blue. Probably you already used the script.

**Comment by trymeouteh** [comment]
My bad, your right the default color is blue. How can I change it to green? Is this possible to do with folder-colors?

**Comment by SmartFinn** [comment]
> How can I change it to green? Is this possible to do with folder-colors?

To change the folder color to Green just run the command:

```
papirus-folders -u -C green --theme Papirus
```

> Is there a way to have a Papirus-Green theme that I can setup?

The command above is enough. You'll get Papirus icon theme with Green folders by default.

**Comment by trymeouteh** [comment]
```
$ papirus-folders -u -C green --theme Papirus
papirus-folders: command not found
```
When I enter this command it says "command not found"

**Comment by SmartFinn** [comment]
You have to install first. Run the following command:

```bash
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/master/install.sh | sh
```

And then run that command to change color.

**Comment by trymeouteh** [comment]
Thank you. My last question is, does this papirus-folders script/app require foldor-color?

http://foldercolor.tuxfamily.org/

**Comment by SmartFinn** [comment]
> My last question is, does this papirus-folders script/app require foldor-color?

No, it not.
