### ISSUE TITLE
Does papirus-folders act only system-wide ?

### ISSUE THREAD

**Issue by Coeur-Noir** [PapirusDevelopmentTeam/papirus-folders#15]
Hi,

using papirus-folders here on a Ubuntu Budgie 18.04.

When using it to change the folders default color - let's say to orange - it's applied system-wide to all the sessions / users making use of papirus icons.

Is this intended ?

Or is there a way to set default color for folders per session / per user ?

**Comment by SmartFinn** [comment]
That depends on where Papirus icon theme is installed. If the icons installed to the home directory then papirus-folders applied the color to the user, if to root - system-wide.

To solve this issue just install another copy of Papirus icon theme to the user's [home directory](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#home-directory-for-gtk) and change folder color with `papirus-folders` command. (`sudo papirus-folders`, in this case, changes colors for system-wide).

**Comment by Coeur-Noir** [comment]
Mmm… Does not seem to work. I first installed Papirus system-wide. Then change color, papirus-folder asked me for root password. My folders are grey in all sessions.

Now I have also copied Papirus* into ~/.icons of each user. Run papirus-folder no longer asks for root password but change is not applied, folders color is still the one previously set using root password.

Should I delete Papirus* from /usr/share/local/icons to have it installed only per user side ?

**Comment by SmartFinn** [comment]
I just tested on my system (GNOME Shell 3.32.2) it works as expected. Icons installed to `$HOME/.icons` have higher priority than the system's icons. Maybe the problem related to Budgie. I have to check this.

`papirus-folders -l` shows the chosen color or a default? If the chosen one then try to update caches for all themes with `papirus-folders -uv`.

**Comment by SmartFinn** [comment]
On Ubuntu Budgie 18.10 works fine. The system folders are gray, the user's folders are cyan:

![image](https://user-images.githubusercontent.com/819186/69973077-8d806380-152b-11ea-8665-71c68088029a.png)

![image](https://user-images.githubusercontent.com/819186/69973381-15666d80-152c-11ea-9536-bb67b360255f.png)

**Comment by Coeur-Noir** [comment]
Sorry… did all that and still not ok.
![Capture du 2019-12-02 16-53-31](https://user-images.githubusercontent.com/1895947/69974089-db459d80-1524-11ea-8102-b653255cce17.png)
![Capture du 2019-12-02 16-54-31](https://user-images.githubusercontent.com/1895947/69974115-e4366f00-1524-11ea-9564-0ddbbb240460.png)
![Capture du 2019-12-02 16-57-11](https://user-images.githubusercontent.com/1895947/69974123-e8fb2300-1524-11ea-826e-20f85afca7f7.png)
Of course I quit and relaunch nautilus each time.
Even did I quit session and log in again…

**Comment by SmartFinn** [comment]
You didn't mention that you using Unity. So Unity doesn't use icons from `~/.icons`. Try to delete the themes from `$HOME/.icons` and install them to `$HOME/.local/share/icons` ([link](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#home-directory-for-kde)).

**Comment by Coeur-Noir** [comment]
It's another session with Unity on the same system. But I start thinking Unity and Budgie can't live together well… despite being run by different users.

In both sessions, icons are actually installed in ~/.local/share/icons and ~/.icons is a symlink towards it.

**Comment by SmartFinn** [comment]
@Coeur-Noir 

> In both sessions, icons are actually installed in ~/.local/share/icons and ~/.icons is a symlink towards it.

That is the problem. `~/.icons` cannot be a symlink, it must be a directory.

**Comment by Coeur-Noir** [comment]
Aaaww… how strange about the symlink ?

Meanwhile here is what I did to « fix » my issue, while keeping the .icons symlink ( I need it for other themes or icon set ) : 
⋅ completely uninstall everything regarding papirus icons and papirus-folder everywhere,
⋅ installed system-wide papirus icons and papirus-folder,
⋅ run the install script in each user session to install papirrus icons in ~/.icons ( actually ~/.local/share/icons due to my symlink ),
⋅ tried to change color on user side → did not work,
⋅ completely uninstall papirus system side ( but keeping papirus-folder ) so papirus icons are only in each user session and no longer in /usr/share/icons,
⋅ change color per session → now it works, my unity session has orange folders with ambiance theme and my budgie session has grey folders with adapta theme, no more mismatch !

If the script can't follow symlink then it was normal changes were only applied system-wide. What remains weird is I was unable to revert my changes system-wide though.

Next step : get back to an installation without symlink just to confirm everything works as expected. My own mess, lol.

**Comment by SmartFinn** [comment]
Btw, the script works fine with symlinks, but GTK framework totally ignores `~/.icons` when it's a symlink.

**Comment by Coeur-Noir** [comment]
And holly…

I removed my ~/.icons symlinks to replace with real folders.

And as soon as I install papirus icons system-wide, all my folders are blue everywhere…
Even if i re-run _papirus-folders -C this_or_that_ in each session ( without sudo )

![Capture du 2019-12-02 18-28-07](https://user-images.githubusercontent.com/1895947/69981075-d9cea200-1531-11ea-9fd9-e31f5718b254.png)

![Capture du 2019-12-02 18-26-57](https://user-images.githubusercontent.com/1895947/69981120-f36fe980-1531-11ea-8f76-8009e1768abb.png)

**Comment by SmartFinn** [comment]
It seems like a cache issue. Try rebuild cache for user with `papirus-folders -uv` and  for system with `sudo papirus-folders -uv`.

But I recommend you complete remove Papirus icon theme from all locations with `wget -qO- https://git.io/papirus-icon-theme-uninstall | sh` and then install to system and to user with our installation scripts (because our scripts work together with papirus-folders).

**Comment by Coeur-Noir** [comment]
⋅ Uninstalled using `wget -qO- https://git.io/papirus-icon-theme-uninstall | sh` on each session, each time script asked for sudo password.
⋅ Uninstalled then papirus-folders and papirus icons using synaptic

Installed using scripts from here to system ( sudo ) and to users ( no sudo ). This does not bring papirus-folders. Installed it with synaptic ( therefore from ppa ) which also seems to reinstall icons.

Then changed the color on each user side, grey for Budgie, orange for Unity, did the cache thing. No better result : 

![Capture du 2019-12-03 16-21-02](https://user-images.githubusercontent.com/1895947/70064661-3097b280-15ea-11ea-9279-e17a5699f278.png)

![Capture du 2019-12-03 16-18-37](https://user-images.githubusercontent.com/1895947/70064719-486f3680-15ea-11ea-84fc-180937517750.png)

Note that in Unity, Budgie desktop settings only shows one whilst unity-tweak shows twice each Papirus icon-set twice. I've tried both, guessing one is for system end the other for user.

Now if I delete papirus icon-set from system I will have different colors in different sessions but administrative applications ( like synaptic, gparted, etc ) won't have papirus icons…

Is there something broken : 
⋅ in ppa ?
⋅ in my system ?
⋅ only in 18.04 ?

**Comment by SmartFinn** [comment]
@Coeur-Noir but why folders color is blue? I guess there is another copy of Papirus icon theme with blue folders. Maybe it's located in `/usr/local/share/icons` or check Flatpak packages if you used it.

**Comment by Coeur-Noir** [comment]
_but why folders color is blue?_ Errr… that's precisely my problem since the beginning of that discussion ;-)

As soon as papirus-icons are installed system-side, the chosen color user-side is not applied.

If I delete papirus-icons from `/usr/local/share/icon`s then it's ok user-side but applications in root-mode ( such as synaptic, gparted ) fall back to ( other ) default icons.

Flatpak… damn those new packages. I'll have to check those also, I may have some.

**Comment by Coeur-Noir** [comment]
I've checked flatpak installed on my system, no package related to papirus-icon there.

Budgie 18.10 ( and up ) have Nemo as file explorer. It is Nautilus in 18.04 : can it be a reason ?

**Comment by SmartFinn** [comment]
![image](https://user-images.githubusercontent.com/819186/70801828-989f8300-1db8-11ea-8c43-d1e03c1ae401.png)

Seems I found what the problem was. As you see on the screenshot sudo pass `$HOME` to root environment. It's never happened in interactive mode (`sudo -i`), so I didn't know that.

So every time you run `sudo papirus-folder` it changes colors in `~/.icons/` and breaks permissions on symlinks and on icon-theme.cache file. That is why you got the blue folders.

Unfortunately, that is not all. In Unity `~/.icons` directory has lower priority than `/usr/share/icons`. Even when a different order is specified in the [specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout).

To fix that you have to:

```sh
### In Bugie:
# 1. Delete Papirus icons from ~/.icons and config file (because permissions corrupted)
sudo rm -rf ~/.icons/{Papirus,Papirus-Dark,Papirus-Light,ePapirus}
sudo rm -rf ~/.config/papirus-folders/
# 2. Install it again
wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR="$HOME/.icons" sh
# 3. Change folders color for Budgie session
papirus-folders -v -C grey -t Papirus -u
### In Unity:
# 1. Delete Papirus icons from ~/.icons and config file (because permissions corrupted)
sudo rm -rf ~/.icons/{Papirus,Papirus-Dark,Papirus-Light,ePapirus}
sudo rm -rf ~/.config/papirus-folders/
# 2. Change folders color to orange for system-wide with `sudo -H`
sudo -H papirus-folders -v -C orange -t Papirus -u
```

**Comment by Coeur-Noir** [comment]
…and as soon as I did `sudo -H papirus-folders -v -C orange -t Papirus -u` in my unity session I ended up with orange folders everywhere…

The user preference in Budgie session seems overridden by the one set with sudo.
![Capture du 2019-12-14 22-55-23](https://user-images.githubusercontent.com/1895947/70855082-1486f180-1ec5-11ea-8e43-043f5f40b10e.png)

**Comment by SmartFinn** [comment]
I recommended you remove and install Papirus icons to `~/.icons` in Budgie session did you do it?

Check permissions on files:

```
ls -l ~/.icons/Papirus/icon-theme.cache
ls -l ~/.config/papirus-folders/keep
```

**Comment by Coeur-Noir** [comment]
_I recommended you remove and install Papirus icons to ~/.icons in Budgie session did you do it?_
→ yes I did.
```
coeur-noir@asgard:~$ ls -l ~/.icons/Papirus/icon-theme.cache
-rw-r--r-- 1 coeur-noir maison 1961448 déc.  14 23:09 /home/coeur-noir/.icons/Papirus/icon-theme.cache
coeur-noir@asgard:~$ ls -l ~/.config/papirus-folders/keep
-rw-r--r-- 1 coeur-noir maison 25 déc.  14 23:09 /home/coeur-noir/.config/papirus-folders/keep
coeur-noir@asgard:~$ 
```
Now I have also totally deleted the Unity session and its user, and even reinstalled budgie-core, budgie-desktop and so on but…
![Capture du 2019-12-14 23-15-06](https://user-images.githubusercontent.com/1895947/70855246-28802280-1ec8-11ea-8ec6-c03f1674ea5a.png)

**Comment by SmartFinn** [comment]
Interesting, it worked for me https://github.com/PapirusDevelopmentTeam/papirus-folders/issues/15#issuecomment-560454812

Is `~/.icons` directory not a symlink?

**Comment by Coeur-Noir** [comment]
```coeur-noir@asgard:~$ ls -la
total 424
drwxrwsr-x 38 coeur-noir maison   4096 déc.  14 23:12  .
drwxr-xr-x 11 root       root     4096 déc.  14 23:06  ..
(…)
-rw--wS---  1 coeur-noir maison 146714 déc.  14 22:40  .ICEauthority
drwxrwsr-x  6 coeur-noir maison   4096 déc.  14 22:27  .icons
lrwxrwxrwx  1 coeur-noir maison     22 juin   2  2018  Images -> /home/coeurnoir/Images
drwx------  3 coeur-noir maison   4096 juil. 25  2018  .launchpadlib
(…)
-rw--wS---  1 coeur-noir maison     51 déc.  14 22:40  .Xauthority
-rw-rwSr--  1 coeur-noir maison    131 juin   2  2018  .xinputrc
-rw-------  1 coeur-noir maison   4335 déc.  14 22:40  .xsession-errors
-rw-------  1 coeur-noir maison   4335 déc.  14 22:24  .xsession-errors.old
coeur-noir@asgard:~$ 
```
`.icons` is not a symlink but a _real_ directory.

Wondering if 18.04 might be different to 18.10 or 19.10 regarding that matter… if I try, I'll let you know.

Or maybe Nautilus vs. Nemo ?

**Comment by SmartFinn** [comment]
> Or maybe Nautilus vs. Nemo ?

No matter what FM/app do you use. It's related to Desktop Environment, more precisely, it is related to a framework on which DE is built.

> Wondering if 18.04 might be different to 18.10 or 19.10 regarding that matter… if I try, I'll let you know.

Yeah, it doesn't work on Ubuntu Budgie 18.04. Seems older versions of the GTK framework do not follow the specification.

But this is not the end. There is another way to get what you want:

1. Remove Papirus icons from `/usr/share/icons`:
	```
	wget -qO- https://git.io/papirus-icon-theme-install | uninstall=true sh
	```
2. Install the icons to `/root/.icons`:
	```
	wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR=/root/.icons sh
	```
3. Login to Unity session, install the icons and then change folders color to orange:
	```
	wget -qO- https://git.io/papirus-icon-theme-install | DESTDIR=~/.icons sh
	papirus-icons -v -C orange -u
	```

That's it. Unity uses icons from `/home/gm-1004/.icons`, Budgie uses icons from `/home/coeur-noir/.icons`, applications running with sudo get icons from `/root/.icons`

**Comment by Coeur-Noir** [comment]
Yes, good catch ! Now I can set a color for root user system wide ( grey ) and one different color per user ( teal, blue… )

So **everything's fine in 18.04 as long as you DO NOT install Papirus system wide** inside `/usr/share/icons` although it's the normal default place for icons in system, it seems to override any other user place for icons.

So if you install them in `/root/.icons` beware you won't find Papirus icons theme user side ( ie. in your usual desktop settings ) UNLESS you also install them in each personal user's folder `~/.icons`

It's not optimal as it copies / duplicates many files but at least it works.

Many thanks for your patience and perseverance @SmartFinn !

**Comment by Coeur-Noir** [comment]
Mmm… upgraded to 20.04 since and I find again same behavior.

If I run folder-color user-side, new color is applied system-wide.

Ok, I will install in each user's personal folder instead…
