### ISSUE TITLE
How to add a mark or symbol to a folder.

### ISSUE THREAD

**Issue by mansoorahmedme** [PapirusDevelopmentTeam/papirus-folders#16]
I want to add a mark or folder in my newly created folder i.e. the one I created, just like the default folders of ubuntu e.g. Pictures, Downloads, Documents, Videos, Music etc. How can I do that.
![Screenshot](https://user-images.githubusercontent.com/60285282/78106587-21e0d100-740d-11ea-8847-761bab720914.png)

**Comment by SmartFinn** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/2124
