### ISSUE TITLE
Yaru color is not available

### ISSUE THREAD

**Issue by Teraskull** [PapirusDevelopmentTeam/papirus-folders#17]
I am using version 1.7.0, in `papirus-folders -l`,
"yaru" is not in the list.

Error message:  Unable to find 'yaru' color in 'Papirus'.

**Comment by SmartFinn** [comment]
Just update [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#papirus-installer) from master branch.

**Comment by Teraskull** [comment]
> Just update [papirus-icon-theme](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#papirus-installer) from master branch.

Thank you, it worked. Strange, as I made a clean install of the theme literally 5 minutes ago, didn't think it needs to update.

**Comment by SmartFinn** [comment]
@Teraskull 

> Strange, as I made a clean install of the theme literally 5 minutes ago

From there [`ppa:papirus/papirus`](https://launchpad.net/~papirus/+archive/ubuntu/papirus)? The repo contains stable builds that released once a month. The yaru folders will be there in June.

**Comment by Teraskull** [comment]
> @Teraskull
> 
> > Strange, as I made a clean install of the theme literally 5 minutes ago
> 
> From there [`ppa:papirus/papirus`](https://launchpad.net/~papirus/+archive/ubuntu/papirus)? The repo contains stable builds that released once a month. The yaru folders will be there in June.

Oh, I see, yes, I used the ppa, thanks for the info
