### ISSUE TITLE
Get rid of inetutils dependecy

### ISSUE THREAD

**Issue by jetthusher** [PapirusDevelopmentTeam/papirus-folders#18]
Good day to you!
Checked PKGBUILD and noticed that there's inetutils package in the dependencies. It seems strange to me that a bash script for changing colours of folders will not work without networking library.

The only mention of using its binaries was in the papirus-folders script for the intention of determining user hostname, or at least that's what I've found.

https://github.com/PapirusDevelopmentTeam/papirus-folders/blob/84007c1590bbbba105bb94c0a0343ff8b3dbc811/papirus-folders#L351

Can we work with just `cat /etc/hostname` or remove the need of the user hostname altogether? Would love to hear your thought on that.

P.S. Thank you very much for your work on papirus! I love it!

**Comment by SmartFinn** [comment]
Thanks for pointing this out. I was sure that the hostname is part of coreutils, but it is not. I think removing the line is the best option.
