### ISSUE TITLE
Latest version install, missing colors

### ISSUE THREAD

**Issue by ckuenz587** [PapirusDevelopmentTeam/papirus-folders#19]
I may be missing something really simple, but I installed papirus icons and papirus-folders on linuxmint 20 with cinnamon DE. I'm missing the breeze folder color. Is it only available in KDE Plasma or am I missing something?

**Comment by SmartFinn** [comment]
No, it's available anywhere. Did you install both packages from PPA or with Papirus Installer? Make sure that you have new versions of papirus-folders (1.8.0) and papirus-icon-theme (20200901).

**Comment by ckuenz587** [comment]
I did not install it through PPA. I installed the icon pack through Mint's package installer and the folders through .deb file. I removed both and reinstalled both through PPA and everything works. Thank you for getting back to me.

**Comment by cosmin-craciun** [comment]
I'm facing the same issue, albeit with the 'purple' color. Installed and re-installed both papirus-folders and the papirus icon theme through the scripts available on their respective pages

> [cosmin@xps-13:~]$ papirus-folders --version 
>papirus-folders 1.8.0
>[cosmin@xps-13:~]$ papirus-folders -C purple
>papirus-folders: Error: Unable to find 'purple' color in 'Papirus'
