### ISSUE TITLE
Fedora 28 installation istructions?

### ISSUE THREAD

**Issue by Warmuser** [PapirusDevelopmentTeam/papirus-folders#2]
Sorry to disturb you, but I'm confused on how to install these software without a guide. I'm not very expert user, so I need a textual guide to understand how to install some packages.

**Comment by SmartFinn** [comment]
Currently is no package for Fedora distro but you can use universal installation method by running the command in your terminal:

```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-folders/master/install.sh | sh
```

**Comment by Warmuser** [comment]
Ah ok, I expected something with the GUI.

**Comment by Warmuser** [comment]
Ok, I tried but the Folders are still blue 

[newuser@localhost ~]$ su
Password: 
[root@localhost newuser]# papirus-folders -l --theme Papirus-Adapta
List of available colors:

   black
   blue
   brown
 > cyan
   green
   grey
   magenta
   orange
   red
   teal
   violet
   yellow

[root@localhost newuser]# papirus-folders -C brown --theme Papirus-Adapta
papirus-folders: Changing color of folders to 'brown' for 'Papirus-Adapta' ...
[root@localhost newuser]# 

Maybe is why the supported theme supported is only papirus-adapta?

Personally I use these [icon package](https://www.opendesktop.org/p/1166289/)

**Comment by SmartFinn** [comment]
No need run the script from root user, espesially if icon theme installed into home directory.

> Ok, I tried but the Folders are still blue

Make sure that Papirus icons were NOT installed in two or more places (root and home directory for example).

> Maybe is why the supported theme supported is only papirus-adapta?

papirus-folders supports all Papirus variants and forks.

**Comment by SmartFinn** [comment]
@Warmuser if still no success I recommend you uninstall all Papirus installation and install a new one from upstream:

#### Uninstall

```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/uninstall.sh | sh
```

#### Install from GitHub

```
wget -qO- https://raw.githubusercontent.com/PapirusDevelopmentTeam/papirus-icon-theme/master/install.sh | sh
```

#### Change folders color to brown

```
papirus-folders -C brown --theme Papirus-Adapta
```

Don't forget choose Papirus-Adapta theme in the Settings/Tweak Tool.

**Comment by Warmuser** [comment]
Ok, thanks! :)
