### ISSUE TITLE
"Videos" folder in the Home directory doesn't change color (Papirus-Dark-Maia)

### ISSUE THREAD

**Issue by imacasualguy** [PapirusDevelopmentTeam/papirus-folders#21]
The (Manjaro) Papirus-Dark-Maia theme "Videos" folder in the Home directory doesn't change into any color, it does in all the others including hidden folders and this is not the case with the Papirus-Dark theme which does it correctly.

![Papirus-folders](https://user-images.githubusercontent.com/49039775/103160908-48c00e00-47b9-11eb-946b-483d3470b922.png)

**Comment by varlesh** [comment]
check on Videos hidden file `.directory`. Open on text editor and see line `Icon=`

**Comment by imacasualguy** [comment]
Searched and I haven't found any hidden .directory file inside Videos, it's completely empty, even outside in the Home folder.

**Comment by varlesh** [comment]
Anyway, we not support Papirus-Dark-Maia. We support original Papirus.
Maybe @Ste74 help you

**Comment by imacasualguy** [comment]
Don't worry is not a big deal. I've changed to Papirus-Dark with no noticeable inconvenience, open the issue just to know if it was a problem with papitus-folders but it doesn't seem to be, I should post elsewhere. 

Thanks for your time.

**Comment by MathisP75** [comment]
I have the same issue with other themes...
