### ISSUE TITLE
Error with installing papirus-folders 

### ISSUE THREAD

**Issue by Nakamerica** [PapirusDevelopmentTeam/papirus-folders#26]
Distro - Ubuntu 20.04 LTS 
installing method - PPA 
Hi, i was trying to install this on my system, but I'm getting the error in the screenshot below. 

Would really appreciate if I could get some help with this... I'm a complete beginner and I've been trying to figure this out for hours now.
![Screenshot from 2021-12-31 19-36-25](https://user-images.githubusercontent.com/88226614/147827477-0fe0a7ce-7052-4065-ae4d-cf46dc6848ea.png)

**Comment by Nakamerica** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/1494

i was looking around and this question seems similar to mine, I wonder if this helps in any way...

**Comment by SmartFinn** [comment]
Seems you did install the package and then remove the script. Try reinstall the package with the following command:

```sh
sudo apt install --reinstall papirus-folders
```

> i was looking around and this question seems similar to mine, I wonder if this helps in any way...

Not even close.

**Comment by Nakamerica** [comment]
Thank you for taking the time to reply 
> Seems you did install the package and then remove the script. Try reinstall the package with the following command:
Yes, i installed, uninstalled and then reinstalled it again in the hopes of making it work. 
i ran the cmd you mentioned, then the `papirus-folders -C brown --theme Papirus-Dark` cmd, this is what shows up 


![Screenshot from 2021-12-31 20-51-23](https://user-images.githubusercontent.com/88226614/147830369-80edadb0-1b80-4060-a833-e651eb97fbfa.png)



> Not even close.
I see.

**Comment by SmartFinn** [comment]
Now do the same with `papirus-icon-theme` package:

```
sudo apt install --reinstall papirus-icon-theme
```

**Comment by Nakamerica** [comment]
ah thank you so much, it looks fantastic.

**Comment by Nakamerica** [comment]
one more question if you could help me with it: Is it possible to use your theme just for folders with a different icon theme otherwise? I'm assuming that's not possible?

**Comment by SmartFinn** [comment]
You will be surprised. It's not so hard to do.

1. Install the fork [FreaxMATE/papirus-mate-icon-theme](https://github.com/FreaxMATE/papirus-mate-icon-theme#root-directory-recommended)
2. Replace `Inherits=Papirus-Dark,Papirus,gnome,hicolor` line to `Inherits=YOUR_THEME_NAME,gnome,hicolor` in the following files:
	- /usr/share/icons/Papirus-MATE-Dark/index.theme
	- /usr/share/icons/Papirus-MATE/index.theme
	- /usr/share/icons/Papirus-MATE-Light/index.theme
3. Update icon cache for the themes with the command
	```
	sudo gtk-update-icon-cache -f /usr/share/icons/Papirus-MATE-Dark /usr/share/icons/Papirus-MATE /usr/share/icons/Papirus-MATE-Light
	```
4. Done.

But please don't come back asking for support for this configuration :wink:

**Comment by Nakamerica** [comment]
I see, thank you for the writeup, and of course, I'll leave you alone now haha
