### ISSUE TITLE
Possible to include the new (yet to be released) adwaita-icon-theme blue folders?

### ISSUE THREAD

**Issue by Scotty-Trees** [PapirusDevelopmentTeam/papirus-folders#27]
Greetings,

I was just wondering if it would be possible or likely for papirus-folders to include the new blue folder icons when Gnome 42 is released? For context I'm referring to the issue and the merge links here:

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/126

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/merge_requests/32

What the folder icons in question look like is below:

![Screenshot_from_2021-10-06_18-23-36](https://user-images.githubusercontent.com/45135187/151681043-67dc3f09-cde5-48a7-a5d9-7c652a5e2953.png)

Please let me know if this is something you might consider as I think the new icons help with contrast with the dark theme. I don't prefer the adwaita-icon set myself, which is why I love to use both papirus-icon-theme and papirus-folders together, hence my inquiry into this. No worries if it can't be done, I'm simply just curious and hopeful is all. In any case, thanks for making this folders package, it's always one of the first things I install on a new system.

**Comment by gregorydk** [comment]
Yes. Since there is a Yaru and Nordic variant, an Adwaita variant seems logical and would be appreciated.
The screenshot was an early version though, the current design has slightly changed (less green).
![folder](https://user-images.githubusercontent.com/7804464/155600296-93528461-345b-41ab-9b75-e6d1ea0691d7.png)
![folder-documents](https://user-images.githubusercontent.com/7804464/155600316-c608cd4a-c7f8-4c6f-bb4c-8b239fee969d.png)

**Comment by Scotty-Trees** [comment]
I know it's hard to tell in a text form, but I am very very happy to read this. Take all the time you need of course to figure it out, tweak it, and implement it, there's no rush by any means to have it out by a certain point. It's ready when it's ready is fine with me.

**Comment by varlesh** [comment]
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/commit/777dbc6c30fce83af51c7dad4c503811cb322e0a

**Comment by Scotty-Trees** [comment]
Just saw the new release for the new adwaita colors. I'm on EndeavourOS using the AUR, so once the maintainer updates it, I'll looking forward to using it. Just wanted to say thank you very very much for making this happen, I truly appreciate your time, efforts, and work making some of the best folder options out there! Thank you :)

**Comment by gregorydk** [comment]
@Scotty-Trees As for papirus-folder, add adwaita to the script and you can install it. But it's possible you need some fiddling with clearing cache and resetting to default colour first after installing adwaita.

**Comment by Scotty-Trees** [comment]
![Screenshot from 2022-03-08 17-53-10](https://user-images.githubusercontent.com/45135187/157339478-acc52247-a6f4-40d5-ba5d-f2b095f368f0.png)

Just got the update working now, it's looking wonderful, thanks for all the devs hard work, very very much apprecaited thank you!
