### ISSUE TITLE
Request: Please Change To Install/Run/Work In Users $HOME

### ISSUE THREAD

**Issue by 0pLuS0** [PapirusDevelopmentTeam/papirus-folders#28]
Hello,

Thanks for making this and simplifying the process, especially with smaller 3rd party file managers, but it would be nice if you can please make this to install and run from a users $HOME, instead of installing into the root / of the system.

THANKS

**Comment by SmartFinn** [comment]
I added ability to install to home directory. Run and work were already supported.

```sh
wget -qO- https://git.io/papirus-folders-install | env PREFIX=$HOME/.local sh
```
