### ISSUE TITLE
I ask your authorisation to fork this development and to modify for my own theme

### ISSUE THREAD

**Issue by gusbemacbe** [PapirusDevelopmentTeam/papirus-folders#3]
Hello @SmartFinn and @varlesh !

I would like to fork your shell script and modify it for my own icons theme which comes with colourful folders.

Gustavo

**Comment by SmartFinn** [comment]
Sure, do anything the MIT license permits. Also, look on [build_color_folders.sh](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/tools/build_color_folders.sh) script, that allows to build icons by color replacing and creating symlinks for [Folder color](http://foldercolor.tuxfamily.org/).

Feel free to ask me for adapting the scripts to your icon theme.

**Comment by gusbemacbe** [comment]
Hi @SmartFinn !

The `papirus-folders` is very easy than `build_color_folders.sh`. In the file `build_color_folders.sh my folders icons have more than 5 colours than your folders icons with just 4 colours. 

I have tested and it worked. Here are two screenshots:

![result1](https://user-images.githubusercontent.com/2257024/44940813-e336f080-ad69-11e8-9059-a2e229b29fab.png)

![result2](https://user-images.githubusercontent.com/2257024/44940816-e8943b00-ad69-11e8-936c-e3db8da35668.png)

I have a doubt. Does it work with all file managers (Caja, Dolphin, Nemo, Thunar, etc.)? 

Thank you for your authorisation!

**Comment by SmartFinn** [comment]
@gusbemacbe

> I have a doubt. Does it work with all file managers (Caja, Dolphin, Nemo, Thunar, etc.)?

Yes. It works with any FM and any DE. The script creates/changes symlinks in the icon theme directory and updates icon cache. The weakness of this method is the need to restore the selected folder color after each update. We do it in our installation script https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/install.sh#L79 and in our deb package https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/packaging/debian/postinst#L33

**Comment by SmartFinn** [comment]
@gusbemacbe I'll help you to adaptive `build_color_folders.sh` script for your icon theme. I see a lot of issue in https://github.com/gusbemacbe/suru-plus should I open PR in https://github.com/gusbemacbe/suru-plus-alpha?

Icons in `places/16` and `places/symbolic` no need a color suffix, because they don't have a colors.

> my folders icons have more than 5 colours

I see only 3 color, the others colors are white with differ opacity value.

**Comment by gusbemacbe** [comment]
@SmartFinn 

> The weakness of this method is the need to restore the selected folder color after each update. We do it in our installation script https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/install.sh#L79 and in our deb package https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/packaging/debian/postinst#L33

Thank you for the advice. I will give the users who will read tutorial.

> @gusbemacbe I'll help you to adaptive build_color_folders.sh script for your icon theme. I see a lot of issue in https://github.com/gusbemacbe/suru-plus should I open PR in https://github.com/gusbemacbe/suru-plus-alpha?

Yes, please. Suru++ Alpha is for analysing and testing.

Can I know what issues?

> I see only 3 color, the others colors are white with differ opacity value.

Yes, it is. I have difficult to redesign `folder-custom` because of white colours with opacity value.

**Comment by SmartFinn** [comment]
@gusbemacbe 

> Can I know what issues?

> Icons in places/16 and places/symbolic no need a color suffix, because they don't have colors.

That is first. The second is a lot of broken symlinks and typo in icon names. The third is color places icons without a color suffix.

**Comment by gusbemacbe** [comment]
Thank you for reporting. You are free to make a PR, fixing them.
