### ISSUE TITLE
Change color of folders when viewing files and folders in List mode

### ISSUE THREAD

**Issue by advlpr** [PapirusDevelopmentTeam/papirus-folders#30]
Hi. First, thanks for this project, I love how the folders look.

I can see the selected color for folders when viewing files and folders in Grid mode, but when viewing them in List mode the folders are white.

Grid mode
![image](https://user-images.githubusercontent.com/81407164/172533076-0ade88a0-f119-4aa3-b5b3-5515ef5556d9.png)

List mode
![image](https://user-images.githubusercontent.com/81407164/172533226-33bedf04-6346-4cf3-a4b6-ebdb44be7443.png)

Can the same selected color, when running the script, be applied to folders in List mode too?

Pop_OS! 22.04
Nautilus
Papirus Dark

**Comment by varlesh** [comment]
No, becuase on more file managers used this folders on sidebar. But we are wan't multiple colors on sidebar. It's exeption for 16px icons only. For example, dolphin:
![image](https://user-images.githubusercontent.com/8083855/172537656-3e02faa1-f3fc-4c5d-9249-3b6f9a86be62.png)
