### ISSUE TITLE
Autodetect all colors / list of colors is hardcoded

### ISSUE THREAD

**Issue by theCapypara** [PapirusDevelopmentTeam/papirus-folders#31]
Hi! I installed both this and Papirus Nord (https://github.com/Adapta-Projects/Papirus-Nord) through the Arch Linux AUR and was going mad trying to figure out why it didn't list any of Papirus Nord's colors.

Then I looked at the code and realized, that the list of colors is hardcoded and that Papirus Nord ships a fork of papirus-folder.

Is there any reason for the list of valid colors to be hardcoded? Why not auto-detect all available colors instead?

**Comment by SmartFinn** [comment]
The list of colors is not hardcoded. This is a preset of colors.
If anyone has a snippet on how to implement auto-detect, please let me know.

**Comment by SmartFinn** [comment]
The task will be much easier when folder-custom icons will be deleted https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3551
