### ISSUE TITLE
Cannot change colour in a immutable system

### ISSUE THREAD

**Issue by sith-on-mars** [PapirusDevelopmentTeam/papirus-folders#35]
I'm using OpenSUSE MicroOS Gnome, an immutable system that prevents you from editing root files. I installed both the icon theme and folder from OpenSUSE's official repo. Here is the output when I tries to change the folder colour:

```
papirus-folders: Changing color of folders to 'brown' for 'Papirus-Dark' ...
ln: failed to create symbolic link '/usr/share/icons/Papirus-Dark/22x22/places/folder-activities.svg': Read-only file system
papirus-folders: Error: Fail to create '/usr/share/icons/Papirus-Dark/22x22/places/folder-activities.svg' symlink
```

Would there be any workaround? Cheers!

**Comment by SmartFinn** [comment]
Just install Papirus icon theme to [HOME directory](https://github.com/PapirusDevelopmentTeam/papirus-icon-theme#home-directory-for-gtk) and then run again `papirus-folders -C brown -vu`.
