### ISSUE TITLE
Smallest icons sizes for folders in GNOME Files do not follow the desired color scheme

### ISSUE THREAD

**Issue by Ohaa** [PapirusDevelopmentTeam/papirus-folders#36]
The Papirus Icons look fantastic in GNOME Files/Nautilus, but the commands to change the folder icon colors do not seem to affect the folder icons when using the smallest list view (it falls back to gray folder icons no which color scheme). The new folder colors are only visible when increasing the icon size by at least one step.

Is there any chance to also change the folder icons of the minimal icon size in list view to the desired color?

**Comment by SmartFinn** [comment]
See #30 and PapirusDevelopmentTeam/papirus-icon-theme#2088
