### ISSUE TITLE
How to use the "custom" color?

### ISSUE THREAD

**Issue by fblais** [PapirusDevelopmentTeam/papirus-folders#42]
HI.
Using the -l command-line option, I see the "custom" entry.
But how to use it?
I tried -C custom but got black icons, so I suppose I need to provide the custom color somewhere.
But where, and how?

Thanks in advance!

**Comment by SmartFinn** [comment]
The `folder-*-custom` icons have been removed from Papirus icon theme. They used in [Folder Color](https://github.com/costales/folder-color/), an app for changing color of individual folder. See https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/issues/3551
