### ISSUE TITLE
Cannot change folders' colour

### ISSUE THREAD

**Issue by lamhm** [PapirusDevelopmentTeam/papirus-folders#7]
The tool is broken after the commit [8d75a871ae8bc3794844037402d03bb8451caae8](https://github.com/PapirusDevelopmentTeam/papirus-folders/commit/8d75a871ae8bc3794844037402d03bb8451caae8#diff-7b87ea2a84a8c048424bc4ae1bc27cce).

Now, every time I try to change folders' colour, the following error message is thrown:
`/usr/bin/papirus-folders: line 258: mapfile: -d: invalid option`
`mapfile: usage: mapfile [-n count] [-O origin] [-s count] [-t] [-u fd] [-C callback] [-c quantum] [array]`

**Comment by SmartFinn** [comment]
Show me the output of the following commands:

```
cat /etc/os-release
bash --version
```

**Comment by lamhm** [comment]
Hi @SmartFinn,

I should have left the info for you to debug. Sorry about that. Here it is:

```
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

```
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
```

Thanks a lot.

**Comment by SmartFinn** [comment]
I fixed it by replaced find command to for-loop statement. Now, no needs to use `mapfile -d` or `while read`.
